"""
Sync V1 — Data models using Python dataclasses only.

No database dependencies. No ORM. No persistence layer.
All models are plain dataclasses for local validation and
JSON serialization.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from typing import Any, Optional


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


@dataclass(frozen=True)
class FundSnapshot:
    """
    A point-in-time snapshot of a fund's market data.

    Sources: BrsProvider.get_symbol(), BrsProvider.get_nav(),
    BrsProvider.get_all_symbols() — existing provider interface only.
    No new provider code is touched.
    """

    symbol: str
    name: str
    ins_code: str
    isin: Optional[str] = None
    sector: Optional[str] = None

    # Market data
    last_price: Optional[float] = None
    close_price: Optional[float] = None
    yesterday_price: Optional[float] = None
    change_last_pct: Optional[float] = None
    volume: Optional[float] = None
    value: Optional[float] = None

    # NAV (fund-specific)
    nav_issue: Optional[float] = None
    nav_redeem: Optional[float] = None
    nav_date: Optional[str] = None

    # Order book summary (top-of-book only — lightweight)
    best_bid: Optional[float] = None
    best_ask: Optional[float] = None
    bid_volume: Optional[float] = None
    ask_volume: Optional[float] = None

    # Metadata
    source: str = "brs"
    captured_at: str = field(default_factory=_now_iso)
    raw: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        # Remove raw from serialization if too large
        d["raw"] = {}
        return d

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), ensure_ascii=False, default=str)

    def checksum(self) -> str:
        return _sha256_hex(self.to_json().encode("utf-8"))


@dataclass(frozen=True)
class SyncBatch:
    """
    A collection of FundSnapshots ready for sync.

    A batch is the unit of transfer between collector and
    the external server. It contains metadata for retry
    and deduplication.
    """

    batch_id: str
    source: str = "iran-gateway"
    target: str = "external-server"
    snapshots: tuple[FundSnapshot, ...] = ()
    created_at: str = field(default_factory=_now_iso)
    checksum: str = ""
    compressed_size: int = 0
    status: str = "pending"  # pending | sent | acked | failed

    def __post_init__(self) -> None:
        if not self.checksum and self.snapshots:
            object.__setattr__(
                self,
                "checksum",
                _sha256_hex(
                    json.dumps(
                        [s.checksum() for s in self.snapshots],
                        sort_keys=True,
                    ).encode("utf-8")
                ),
            )

    def to_dict(self) -> dict[str, Any]:
        return {
            "batch_id": self.batch_id,
            "source": self.source,
            "target": self.target,
            "snapshot_count": len(self.snapshots),
            "created_at": self.created_at,
            "checksum": self.checksum,
            "compressed_size": self.compressed_size,
            "status": self.status,
        }

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), ensure_ascii=False)


@dataclass(frozen=True)
class SyncManifest:
    """
    Metadata for a sync batch, generated by the exporter
    and chunker. Used by the receiver to validate and
    reassemble the batch.

    Contains no sensitive data — safe to transmit alongside
    the chunk payload.
    """

    batch_id: str
    total_chunks: int
    chunk_size: int
    checksum: str
    created_at: str = field(default_factory=_now_iso)
    snapshot_count: int = 0
    source: str = "iran-gateway"
    target: str = "external-server"

    def to_dict(self) -> dict[str, Any]:
        return {
            "batch_id": self.batch_id,
            "total_chunks": self.total_chunks,
            "chunk_size": self.chunk_size,
            "checksum": self.checksum,
            "created_at": self.created_at,
            "snapshot_count": self.snapshot_count,
            "source": self.source,
            "target": self.target,
        }

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), ensure_ascii=False)

    def verify_chunk(self, chunk: "SyncChunk") -> bool:
        """Verify a chunk belongs to this manifest."""
        return (
            chunk.batch_id == self.batch_id
            and chunk.total_chunks == self.total_chunks
            and chunk.checksum == self.checksum
        )


@dataclass(frozen=True)
class SyncChunk:
    """
    A single chunk of a compressed batch payload.

    Chunks enable resumable transfer: if a chunk fails,
    only that chunk needs retransmission, not the entire batch.
    """

    chunk_id: str
    batch_id: str
    chunk_index: int
    total_chunks: int
    data: bytes  # compressed payload bytes for this chunk
    checksum: str = ""
    size_bytes: int = 0
    attempts: int = 0
    last_attempt_at: Optional[str] = None
    status: str = "pending"  # pending | sent | acked | failed

    def __post_init__(self) -> None:
        if not self.checksum:
            object.__setattr__(
                self,
                "checksum",
                _sha256_hex(self.data),
            )
        if self.size_bytes == 0:
            object.__setattr__(self, "size_bytes", len(self.data))

    def to_dict(self) -> dict[str, Any]:
        return {
            "chunk_id": self.chunk_id,
            "batch_id": self.batch_id,
            "chunk_index": self.chunk_index,
            "total_chunks": self.total_chunks,
            "size_bytes": self.size_bytes,
            "checksum": self.checksum,
            "attempts": self.attempts,
            "status": self.status,
        }

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), ensure_ascii=False)



